---

- name: Configure UFW
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"

- name: Set UFW Defaults
  ufw:
    direction: "{{ item.direction }}"
    default: "{{ item.default }}"
  loop:
    - { direction: incoming, default: deny }
    - { direction: outgoing, default: allow }

- name: Enable UFW
  ufw:
    state: enabled
