---

- name: Firewall | Configure UFW
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"

- name: Firewall | Set UFW Defaults
  community.general.ufw:
    direction: "{{ item.direction }}"
    default: "{{ item.default }}"
  loop:
    - { direction: incoming, default: deny }
    - { direction: outgoing, default: allow }

- name: Firewall | Enable UFW
  community.general.ufw:
    state: enabled
    logging: '{{ ufw_log_level }}'

- name: Firewall | Configure UFW logrotate
  ansible.builtin.template:
    src: files/logs/ufw.j2
    dest: /etc/logrotate.d/ufw
    mode: '0644'
