---

- name: Packages | Update and Prune
  apt:
    update_cache: yes
    upgrade: 'yes'
    autoremove: yes
    autoclean: yes

- name: Packages | Install - will take a long time
  package:
    name: "{{ apt_packages }}"
    state: present

- name: Packages | Update Gems
  shell: gem update --no-document && touch ~/.ansible-gems-updated
  args:
    creates: ~/.ansible-gems-updated
