---

- name: Packages | Use HTTPS
  ansible.builtin.copy:
    src: files/apt/sources.list
    dest: /etc/apt/sources.list
    mode: '644'

- name: Packages | Update & Upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: 'yes'
  async: 3600
  poll: 30

- name: Packages | Install
  ansible.builtin.package:
    name: "{{ apt_packages }}"
    state: present
  async: 3600
  poll: 30

- name: Packages | Cleanup
  ansible.builtin.apt:
    autoremove: true
    autoclean: true

- name: Packages | Update Gems
  ansible.builtin.shell:
    cmd: gem update --no-document && touch ~/.ansible-gems-updated
    creates: ~/.ansible-gems-updated
