---

- name: Packages | Use HTTPS
  ansible.builtin.copy:
    src: files/apt/sources.list
    dest: /etc/apt/sources.list
    mode: '644'

- name: Packages | Update
  ansible.builtin.apt:
    update_cache: yes
    upgrade: 'yes'

- name: Packages | Install - will take a long time
  ansible.builtin.package:
    name: "{{ apt_packages }}"
    state: present

- name: Packages | Cleanup
  ansible.builtin.apt:
    autoremove: yes
    autoclean: yes

- name: Packages | Update Gems
  ansible.builtin.shell: gem update --no-document && touch ~/.ansible-gems-updated
  args:
    creates: ~/.ansible-gems-updated
