---

- name: System | Ensure Kali user is configured correctly
  ansible.builtin.user:
    name: kali
    password: "{{ kali_user_pass | password_hash('sha512', 'thepasswordisinthevariablesfile') }}"
    state: present
