---

- name: System | Ensure Kali user is configured correctly
  ansible.builtin.user:
    name: kali
    # Hash salt must be less than 16 chars
    # salt too large (sha512_crypt requires <= 16 chars)
    password: "{{ kali_user_pass | password_hash('sha512', 'passinvars') }}"
    state: present
