---
- name: Verify
  hosts: all
  become: true

  tasks:
  - name: Check rockyou wordlist
    ansible.builtin.stat:
      path: /usr/share/wordlists/rockyou.txt
    register: rockyou

  - name: Check for vnc password
    ansible.builtin.stat:
      path: /home/kali/.vnc/passwd
    register: vncpass

  - name: Assertions
    ansible.builtin.assert:
      that:
        - rockyou.stat.exists
        - vncpass.stat.exists
