---
name: Build

on:
  push:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Use Cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          make install-packer
          pip install wheel
          pip install pipenv
          make install

      - name: Packer build
        run: pipenv run packer build kali/kali-ami.json
        env:
          AWS_MAX_ATTEMPTS: 90
          AWS_POLL_DELAY_SECONDS: 60
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
